/** Lead list schema derived from the zip-10024-1010-records.csv template.
 *  Column names are kept EXACTLY as in the source file (used quoted in SQL).
 *  Columns that were entirely empty or entirely 'Not Available' in the
 *  template are excluded from the table. Email is the upsert key. */

export const LEAD_COLUMNS: string[] = [
    "Date List Produced",
    "Record Expiration Date",
    "Title",
    "First Name",
    "Email",
    "Middle Initial",
    "Last Name",
    "Suffix",
    "Address",
    "City",
    "State",
    "ZIP Code",
    "ZIP Plus 4",
    "County Code",
    "County",
    "Metro Area",
    "Metro Area Code",
    "Neighborhood",
    "Carrier Route",
    "Metro / Micro",
    "Latitude",
    "Longitude",
    "Age Range",
    "Adult Gender",
    "Own / Rent",
    "Estimated Household Income",
    "Estimated Home Value",
    "Housing Type",
    "Potential Investor",
    "Wealth Finder",
    "High Tech Household",
    "Internet User",
    "Registered Voter",
    "Political Party",
    "Last Party Contributed To",
    "Congressional District",
    "Home Owner",
    "Years In Home",
    "Year Home Built",
    "Mail Order Purchase",
    "Individual ID",
    "Actual Age",
    "Family ID",
    "Marital Status",
    "Children Present",
    "Number Of Children",
    "Veterans",
    "Ethnicity",
    "Language",
    "Home Sale Date",
    "Home Sale Price",
    "Home Equity Estimate",
    "Finance Type",
    "Home Size",
    "Number Of Bedrooms",
    "Pool Present",
    "Second Property Indicator",
    "Apparel / Fashion / Beauty",
    "Arts / History / Science",
    "Books / Magazines",
    "Charitable Donor",
    "Cooking / Wine",
    "Collectibles",
    "Hobbies / Crafts / Sewing",
    "Gambling / Games / Sweepstakes",
    "Home Improvement / Decor",
    "Motor Vehicles / Motor sports",
    "Outdoor Recreation",
    "Personal Finance / Self-Help",
    "Pets / Animals",
    "Photography",
    "Politics / Religion / News",
    "Purchase Behavior",
    "Sports",
    "Technology / Entertainment",
    "Travel",
    "InfoPersona",
    "Mortgage Present",
    "Mortgage Amount",
    "Mortgage Expense",
    "Mortgage Loan Type",
    "Loan To Value",
    "Tradelines",
    "Landline Number 1",
    "Landline Number 2"
];

export const TEMPLATE_SKIPPED_COLUMNS: string[] = [
    "Lead Status",
    "Tags",
    "Health / Diet / Fitness",
    "Landline Number 3",
    "Landline Number 4",
    "Landline Number 5",
    "Landline Number 6",
    "Landline Number 7",
    "Landline Number 8",
    "Landline Number 9",
    "Landline Number 10"
];
